### ISSUE TITLE
some question about modelnet40

### ISSUE THREAD

**Issue by WangZhouTao** [saaries/PointNet#1]
thank you for your good work.
I want to train classification on modelnet40. But I get some error,
 `FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DataSet\\ModelNet40\\trainval.txt'`
Have you trained the code on modelnet40?
could you tell me where is the trainal.txt file?
looking for your reply.

**Comment by saaries** [comment]
> thank you for your good work.
> I want to train classification on modelnet40. But I get some error,
> `FileNotFoundError: [Errno 2] No such file or directory: 'D:\\DataSet\\ModelNet40\\trainval.txt'`
> Have you trained the code on modelnet40?
> could you tell me where is the trainal.txt file?
> looking for your reply.

For trainal.txt, you may follow the answer in  https://github.com/fxia22/pointnet.pytorch/search?q=txt&unscoped_q=txt&type=Issues

You may also preprocess the ModelNet40 dataset into the same format as the ShapeNet before running the code.

After I finished my report, I did some modifications on the code for some test, so I 'm not sure whether the ModelNet40 part can run smoothly, but the ShapeNet part should work.

**Comment by WangZhouTao** [comment]
thank for your reply. I can train the network on ShapeNet.
