### ISSUE TITLE
Data collected in real scenes

### ISSUE THREAD

**Issue by zhouzhou33** [saaries/PointNet#2]
Thank you very much for your work, I have benefited a lot. Do you use the trained model for your own data later? If you do that, can you give a demo?

**Comment by saaries** [comment]
As I remembered, the training dataset contained a lot of '.pth' files (under every class folder). Each '.pth' stores a 3D point cloud object. 
You can modify your own data into the same structure (or convert other datasets into the same '.pth' format).

The following website will be really helpful for you to check out if the points file actually works.
http://lidarview.com/  (for visualizing point cloud objects).

**Comment by zhouzhou33** [comment]
when I want to run show_seg.py, It said cant't find render_balls_so.dll, but when I try to rebuild render_balls_so.cpp, it said 
D:/mingw-w64/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/lib/../lib/libmingw32.a(lib32_libmingw32_a-crt0_c.o):crt0_c.c:(.text.startup+0x39): undefined reference to `WinMain@16'
collect2.exe: error: ld returned 1 exit status
how could I get the correct  .dll???

**Comment by saaries** [comment]
For Windows platform: I have no idea, I rebuilt render_balls_so.cpp as a dll lib using VS2010 (select x64 compiler), then directly loaded this packed .dll file in python scripts.

I also searched on google for you, it said that python3.8+ has some dll constraints.
Sorry for my limited help : )

Ref: https://github.com/stlehmann/pyads/issues/105

I will check my old PC tonight, maybe I can find out how I solve this problem.

**Comment by saaries** [comment]
@zhouzhou33 
Luckily, I guess I found a solution for you:)
**You don't need to rebuild anything.**

First, in show_balls.py, pass your current work directory to python, by adding the following codes (Just an example, change it to your own directory!!):

> import os
> import sys
> sys.path.append(os.getcwd())
> sys.path.append(r'E:\CityU\CG\CG-pointcloud\master\Pointnet.pytorch-master\utils')
> sys.path.append(r'E:\CityU\CG\CG-pointcloud\master\Pointnet.pytorch-master')
> os.chdir(r'E:\CityU\CG\CG-pointcloud\master\Pointnet.pytorch-master\utils')

Then, pass the full path to LoadLibrary() and use ’r‘ to disable the escape character !!

> from ctypes import*
> dll = cdll.LoadLibrary(r'E:\CityU\CG\CG-pointcloud\master\Pointnet.pytorch-master\utils\render_balls_so.dll')

Wish you good luck!

**Comment by zhouzhou33** [comment]
Thank you very much!!!!!! I will try tomorrow.^^

**Comment by zhouzhou33** [comment]
Still get this error：ImportError: DLL load failed: The specified module could not be found.
This makes me very confused.
Platform I used are:Win10+VScode.
I have another question.When I want to rebuild render_balls_so.cpp,error message seems to remind me that there is no main function????

**Comment by saaries** [comment]
Is that WinError126? I believed that you have some C++ development dependencies missing from your PC.
Try to install contents this link: https://www.microsoft.com/zh-cn/download/confirmation.aspx?id=48145

There are many discussions about the above error in developer communities.
For example, https://stackoverflow.com/questions/1940578/windowserror-error-126-the-specified-module-could-not-be-found
I push the new version of the python scripts, they both worked well on my personal and lib's computer.

I recommend you first try to understand the usage of python.ctypes.LoadLibrary and try some light demo.
By the way, to rebuild the dll library, use visual studio (NOT VSCODE)->New dll project, this is a dll so the main function is not necessary ;)

 (there are many guides on the Internet on how to build a dll, but I am quite sure this is not the dll's problem!!! But this dll cannot found its dependencies which you do not have on your computer).

**Comment by zhouzhou33** [comment]
I use open3d as visualization tool，the effect is not bad. Your help is greatly appreciated.  I'm truly grateful for your help.
