### ISSUE TITLE
About .dll

### ISSUE THREAD

**Issue by dmsobtl** [saaries/PointNet#3]
I have get your code and change the path in file "show3d_balls.py" but it still shows error "Win Error 126". Before get your code, I built the .dll too, but the error still remain. I wonder why the program can't find the .dll. To make the program can be used, I wrote it in python, but it runs really really slow.

**Comment by dmsobtl** [comment]
dll文件明明就放在文件夹里，但是总是提示找不到模块。就是这个显示模块跑起来有问题，分割训练用原作者的码跑起来也没什么问题。目前只能把显示模块用python写了一下拿来用，不过可能是代码效率的问题，跑起来很卡。总的来说github上学习的码大多是在Ubuntu下，看来还是得去搞个linux，这样这种奇怪的问题会少一些

**Comment by saaries** [comment]
Sorry for the inconvenience, but solving the problems we meet when reproducing other people's code are much more meaningful :) @dmsobtl
