### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by chichen-wang** [saaries/PointNet#4]
Hi,

i try to use your code on PyTorch, but I encountered some problems when performing training

Questions are as follows :

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\michael_wang\\Desktop\\PointNet\\PartAnnotation\\train_test_split\\shuffled_train_file_list.json'

Where can I find this file?

**Comment by saaries** [comment]
Hey, I checked the codes. I believed that you're running 'dataset.py' directly, which is wrong.

This part of codes in 'dataset.py' should be called when initializing a class object 'ShapeNetDataset', then I search the keyword 'ShapeNetDataset' in this repository and found that all the initialization of object 'ShapeNetDataset' is assigned with the parameter 'split='test'' (Even though its default parameter is set to 'split='train'').

For example:
` test_dataset = ShapeNetDataset(
        root=opt.dataset,
        classification=True,
        split='test',
        npoints=opt.num_points,
        data_augmentation=False)`

So, do not run 'dataset.py' directly. Instead, use 'python train_classification.py --dataset=data_directory --nepoch=10' or 'python train_segmentation.py --dataset=data_directory --nepoch=5 --outf=path_to_save_trained_model' as requested.

**Comment by chichen-wang** [comment]
Hi,

I only got those errors after using train_classification.py

So I think there should be something that I don’t know or there are steps I didn’t do that would cause the file to be lost

**Comment by chichen-wang** [comment]
![擷取](https://user-images.githubusercontent.com/58201332/129843278-e8fb299e-fdd7-4559-97a5-a89231ef0660.PNG)
This is the error message I see

**Comment by saaries** [comment]
Does it work well when using 'modelnet40'?

**Comment by chichen-wang** [comment]
I also put modelNet40 into the project folder
![擷取](https://user-images.githubusercontent.com/58201332/129843826-2d9da115-9c6b-480b-94a0-03b970f54404.PNG)

**Comment by saaries** [comment]
Maybe you can try to compare your logs with mine as shown in the report [link](https://github.com/saaries/PointNet/blob/master/report.pdf).

**Comment by chichen-wang** [comment]
OK 
I will try it, if there is any problem, I will ask you again

**Comment by chichen-wang** [comment]
hi,

I also encountered the problem that the dll file cannot be opened

How can i fix it

**Comment by saaries** [comment]
Please refer to the [previous issue](https://github.com/saaries/PointNet/issues/2).

**Comment by chichen-wang** [comment]
![擷取](https://user-images.githubusercontent.com/58201332/130398147-2820bdd7-23cf-4ca7-bb4a-fa8a2271d639.PNG)
How can i fix this???

**Comment by chichen-wang** [comment]
i fix this
I can use this program smoothly
Thx

**Comment by saaries** [comment]
Great! You have successfully achieved segmentation. You only need to realize a visualization tool.
Notice that the show3d_balls.py tries to load a DLL file through python code (which is highly possible to encounter unsatisfying problems due to the new features of Python itself).
So, I suggest you read my report, compile this DLL on your own call, and test if it works on your PC.
OR, just use other visualization tool as mentioned in the [previous issue](https://github.com/saaries/PointNet/issues/2).
